config/routes.rb
ActorWebsite::Application.routes.draw do
  root :to => 'pages#home'

  namespace :admin do
    resources :videos
    resources :photos
    resources :blog_posts
    resources :links
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:edit, :update]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/admin',   :to => 'admin#home'

  match '/home',       :to => 'pages#home'
  match '/bio',        :to => 'pages#bio'
  match '/contact',    :to => 'pages#contact'
  match '/news',       :to => 'pages#news'
  match '/photos',     :to => 'pages#photos'
  match '/videos',     :to => 'pages#videos'
  match '/resume',     :to => 'pages#resume'
  match '/links',      :to => 'pages#links'
  match '/photos/:id', :to => 'pages#gallery', :as => 'gallery'

end

app/models/admin/photo.rb
class Admin::Photo < ActiveRecord::Base
  ALBUM_NAMES = %w[headshot still model]

  attr_accessible :album, :caption, :user_id, :picture
  has_attached_file :picture, :styles => { :medium => "600x600", :thumb => "300x300" }

  belongs_to :user

  validates :caption,
            :presence => true

  validates :user_id,
            :presence => true

  validates :album,
            :presence => true

  validates :picture, :attachment_presence => true
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController
  before_filter :authenticate

  # GET /admin/photos
  # GET /admin/photos.json
  def index
    @admin_photos = Admin::Photo.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_photos }
    end
  end

  # GET /admin/photos/1
  # GET /admin/photos/1.json
  def show
    @admin_photo = Admin::Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_photo }
    end
  end

  # GET /admin/photos/new
  # GET /admin/photos/new.json
  def new
    @admin_photo = Admin::Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_photo }
    end
  end

  # GET /admin/photos/1/edit
  def edit
    @admin_photo = Admin::Photo.find(params[:id])
  end

  # POST /admin/photos
  # POST /admin/photos.json
  def create
    @admin_photo = Admin::Photo.new(params[:admin_photo].merge(:user_id => current_user.id))

    respond_to do |format|
      if @admin_photo.save
        format.html { redirect_to @admin_photo, notice: 'Photo was successfully created.' }
        format.json { render json: @admin_photo, status: :created, location: @admin_photo }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/photos/1
  # PUT /admin/photos/1.json
  def update
    @admin_photo = Admin::Photo.find(params[:id])

    respond_to do |format|
      if @admin_photo.update_attributes(params[:admin_photo])
        format.html { redirect_to @admin_photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/photos/1
  # DELETE /admin/photos/1.json
  def destroy
    @admin_photo = Admin::Photo.find(params[:id])
    @admin_photo.destroy

    respond_to do |format|
      format.html { redirect_to admin_photos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/views/admin/photos/_form.html.haml
= form_for @admin_photo, :html => { :multipart => true, :class => 'new-item-form' } do |f|
  - if @admin_photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_photo.errors.count, "error")} prohibited this admin_photo from being saved:"
      %ul
        - @admin_photo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :caption
    = f.text_field :caption
    .clear
  .field
    = f.label :album
    = select("admin_photo", "album", Admin::Photo::ALBUM_NAMES, {:include_blank => false})

  .field
    = f.label :picture
    = f.file_field :picture
    .clear
  .actions
    = f.submit 'Save'

app/views/admin/photos/edit.html.haml
%h1 Edit Photo

= render 'form'

= link_to 'Show Photo', @admin_photo, :class => 'centered styled'
= link_to 'Back to Index', admin_photos_path, :class => 'centered styled'

app/views/admin/photos/index.html.haml
%h1.item-header
  Available Photos

= link_to 'New Photo', new_admin_photo_path, :class => 'styled'

%table.admin
  %tr
    %th Caption
    %th Album
    %th Thumbnail
    %th Options

  - @admin_photos.each do |admin_photo|
    %tr
      %td= admin_photo.caption
      %td= admin_photo.album.capitalize
      %td= link_to image_tag(admin_photo.picture.url(:thumb)), admin_photo.picture.url(:medium), :class => 'fancybox', :'data-pjax-ignore' => 'true', :title => admin_photo.caption, :rel => admin_photo.album
      %td
        = link_to 'Show', admin_photo, :class => 'styled'
        = link_to 'Edit', edit_admin_photo_path(admin_photo), :class => 'styled'
        = link_to 'Destroy', admin_photo, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'styled'
  = render :partial => 'admin/show_pagination', :locals => { :collection => @admin_photos }

%br

app/views/admin/photos/new.html.haml
%h1.item-header
   New Photo

= render 'form'

= link_to 'Back to Index', admin_photos_path, :class => 'centered styled'

app/views/admin/photos/show.html.haml
.admin-show
  %p
    %b Caption:
    = @admin_photo.caption
  %p
    %b User:
    = @admin_photo.user.username
  %p
    %b Album:
    = @admin_photo.album
  %p
    %b Picture:
    = link_to image_tag(@admin_photo.picture(:thumb)), @admin_photo.picture(:medium), :class => 'fancybox',
              :'data-pjax-ignore' => 'true', :title => @admin_photo.caption, :rel => @admin_photo.album

= link_to 'Edit Picture', edit_admin_photo_path(@admin_photo), :class => 'styled centered'
= link_to 'Back to Index', admin_photos_path, :class => 'styled centered'