config/routes.rb
ActorWebsite::Application.routes.draw do
  root :to => 'pages#home'

  namespace :admin do
    resources :videos
    resources :photos
    resources :blog_posts
    resources :links
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:edit, :update]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/admin',   :to => 'admin#home'

  match '/home',       :to => 'pages#home'
  match '/bio',        :to => 'pages#bio'
  match '/contact',    :to => 'pages#contact'
  match '/news',       :to => 'pages#news'
  match '/photos',     :to => 'pages#photos'
  match '/videos',     :to => 'pages#videos'
  match '/resume',     :to => 'pages#resume'
  match '/links',      :to => 'pages#links'
  match '/photos/:id', :to => 'pages#gallery', :as => 'gallery'

end

app/models/admin/video.rb
class Admin::Video < ActiveRecord::Base
  attr_accessible :title, :user_id, :thumbnail, :youtube_url
  has_attached_file :thumbnail, :styles => { :medium => "600x600", :thumb => "300x300" }

  validates :thumbnail, :attachment_presence => true

  def fancybox_url
    youtube_url.gsub("watch?v=", "v/")
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_filter :authenticate

  # GET /admin/videos
  # GET /admin/videos.json
  def index
    @admin_videos = Admin::Video.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_videos }
    end
  end

  # GET /admin/videos/1
  # GET /admin/videos/1.json
  def show
    @admin_video = Admin::Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_video }
    end
  end

  # GET /admin/videos/new
  # GET /admin/videos/new.json
  def new
    @admin_video = Admin::Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_video }
    end
  end

  # GET /admin/videos/1/edit
  def edit
    @admin_video = Admin::Video.find(params[:id])
  end

  # POST /admin/videos
  # POST /admin/videos.json
  def create
    @admin_video = Admin::Video.new(params[:admin_video].merge(:user_id => current_user.id))

    respond_to do |format|
      if @admin_video.save
        format.html { redirect_to @admin_video, notice: 'Video was successfully created.' }
        format.json { render json: @admin_video, status: :created, location: @admin_video }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/videos/1
  # PUT /admin/videos/1.json
  def update
    @admin_video = Admin::Video.find(params[:id])

    respond_to do |format|
      if @admin_video.update_attributes(params[:admin_video])
        format.html { redirect_to @admin_video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/videos/1
  # DELETE /admin/videos/1.json
  def destroy
    @admin_video = Admin::Video.find(params[:id])
    @admin_video.destroy

    respond_to do |format|
      format.html { redirect_to admin_videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/views/admin/videos/_form.html.haml
= form_for @admin_video, :html => { :multipart => true, :class => "new-item-form" } do |f|
  - if @admin_video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_video.errors.count, "error")} prohibited this admin_video from being saved:"
      %ul
        - @admin_video.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
    .clear
  .field
    = f.label :youtube_url
    = f.text_field :youtube_url
    .clear
  .field
    = f.label :thumbnail
    = f.file_field :thumbnail
    .clear
  .actions
    = f.submit 'Save'

app/views/admin/videos/edit.html.haml
%h1.item-header
  Edit Video

= render 'form'

= link_to 'Show Video', @admin_video, :class => 'centered styled'
= link_to 'Back to Index', admin_videos_path, :class => 'centered styled'

app/views/admin/videos/index.html.haml
%h1.item-header
  Video List

= link_to 'New Video', new_admin_video_path, :class => 'styled'

%table.admin
  %tr
    %th Title
    %th Video
    %th Options

  - @admin_videos.each do |admin_video|
    %tr
      %td= admin_video.title
      %td= link_to image_tag(admin_video.thumbnail(:thumb)), admin_video.fancybox_url,
      :class => 'fancybox-video', :'data-pjax-ignore' => 'true', :title => admin_video.title, :rel => 'youtube_video'
      %td
        = link_to 'Show', admin_video, :class => 'styled'
        = link_to 'Edit', edit_admin_video_path(admin_video), :class => 'styled'
        = link_to 'Destroy', admin_video, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'styled'
  = render :partial => 'admin/show_pagination', :locals => { :collection => @admin_videos }


%br

app/views/admin/videos/new.html.haml
%h1.item-header
  New Video

= render 'form'

= link_to 'Back', admin_videos_path, :class => 'centered styled'

app/views/admin/videos/show.html.haml
%p#notice= notice
.admin-show
  %p
    %b Title:
    = @admin_video.title
  %p
    %b Video:
    = link_to image_tag(@admin_video.thumbnail(:thumb)), @admin_video.fancybox_url,
    :class => 'fancybox-video', :'data-pjax-ignore' => 'true', :title => @admin_video.title, :rel => 'youtube_video'

= link_to 'Edit Video', edit_admin_video_path(@admin_video), :class => 'styled centered'
= link_to 'Back to Index', admin_videos_path, :class => 'styled centered'