config/routes.rb
ActorWebsite::Application.routes.draw do
  root :to => 'pages#home'

  namespace :admin do
    resources :videos
    resources :photos
    resources :blog_posts
    resources :links
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:edit, :update]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/admin',   :to => 'admin#home'

  match '/home',       :to => 'pages#home'
  match '/bio',        :to => 'pages#bio'
  match '/contact',    :to => 'pages#contact'
  match '/news',       :to => 'pages#news'
  match '/photos',     :to => 'pages#photos'
  match '/videos',     :to => 'pages#videos'
  match '/resume',     :to => 'pages#resume'
  match '/links',      :to => 'pages#links'
  match '/photos/:id', :to => 'pages#gallery', :as => 'gallery'

end

app/models/admin/blog_post.rb
class Admin::BlogPost < ActiveRecord::Base
  attr_accessible :article, :title, :user_id

  validates :article,
            :presence => true

  validates :title,
            :presence => true
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < ApplicationController
  before_filter :authenticate

  # GET /admin/blog_posts
  # GET /admin/blog_posts.json
  def index
    @admin_blog_posts = Admin::BlogPost.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_blog_posts }
    end
  end

  # GET /admin/blog_posts/1
  # GET /admin/blog_posts/1.json
  def show
    @admin_blog_post = Admin::BlogPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_blog_post }
    end
  end

  # GET /admin/blog_posts/new
  # GET /admin/blog_posts/new.json
  def new
    @admin_blog_post = Admin::BlogPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_blog_post }
    end
  end

  # GET /admin/blog_posts/1/edit
  def edit
    @admin_blog_post = Admin::BlogPost.find(params[:id])
  end

  # POST /admin/blog_posts
  # POST /admin/blog_posts.json
  def create
    @admin_blog_post = Admin::BlogPost.new(params[:admin_blog_post].merge(:user_id => current_user.id))

    respond_to do |format|
      if @admin_blog_post.save
        format.html { redirect_to @admin_blog_post, notice: 'Blog post was successfully created.' }
        format.json { render json: @admin_blog_post, status: :created, location: @admin_blog_post }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/blog_posts/1
  # PUT /admin/blog_posts/1.json
  def update
    @admin_blog_post = Admin::BlogPost.find(params[:id])

    respond_to do |format|
      if @admin_blog_post.update_attributes(params[:admin_blog_post])
        format.html { redirect_to @admin_blog_post, notice: 'Blog post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/blog_posts/1
  # DELETE /admin/blog_posts/1.json
  def destroy
    @admin_blog_post = Admin::BlogPost.find(params[:id])
    @admin_blog_post.destroy

    respond_to do |format|
      format.html { redirect_to admin_blog_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/blog_posts_helper.rb
module Admin::BlogPostsHelper
end

app/views/admin/blog_posts/_form.html.haml
= form_for @admin_blog_post, :html => { :class => 'new-item-form' } do |f|
  - if @admin_blog_post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_blog_post.errors.count, "error")} prohibited this admin_blog_post from being saved:"
      %ul
        - @admin_blog_post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
    .clear
  .field
    = f.label :article
    = f.text_area :article
    .clear
  .actions
    = f.submit 'Save'

app/views/admin/blog_posts/edit.html.haml
%h1.item-header
  Editing Post

= render 'form'

= link_to 'Back to Index', admin_blog_posts_path, :class => 'centered styled'

app/views/admin/blog_posts/index.html.haml
%h1.item-header
  News Entries

= link_to 'New Blog Post', new_admin_blog_post_path, :class => 'styled'

%table.admin
  %tr
    %th Title
    %th Article
    %th Options

  - @admin_blog_posts.each do |admin_blog_post|
    %tr
      %td.title
        = admin_blog_post.title
      %td.left-align
        = simple_format(admin_blog_post.article)
      %td
        = link_to 'Edit', edit_admin_blog_post_path(admin_blog_post), :class => 'styled'
        = link_to 'Destroy', admin_blog_post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'styled'
  = render :partial => 'admin/show_pagination', :locals => { :collection => @admin_blog_posts }

%br

app/views/admin/blog_posts/new.html.haml
%h1 New Post

= render 'form'

= link_to 'Back to Index', admin_blog_posts_path, :class => 'centered'

app/views/admin/blog_posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @admin_blog_post.title
%p
  %b Article:
  = @admin_blog_post.article
%p
  %b User:
  = @admin_blog_post.user_id

= link_to 'Edit', edit_admin_blog_post_path(@admin_blog_post)
\|
= link_to 'Back', admin_blog_posts_path