config/routes.rb
ActorWebsite::Application.routes.draw do
  root :to => 'pages#home'

  namespace :admin do
    resources :videos
    resources :photos
    resources :blog_posts
    resources :links
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:edit, :update]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/admin',   :to => 'admin#home'

  match '/home',       :to => 'pages#home'
  match '/bio',        :to => 'pages#bio'
  match '/contact',    :to => 'pages#contact'
  match '/news',       :to => 'pages#news'
  match '/photos',     :to => 'pages#photos'
  match '/videos',     :to => 'pages#videos'
  match '/resume',     :to => 'pages#resume'
  match '/links',      :to => 'pages#links'
  match '/photos/:id', :to => 'pages#gallery', :as => 'gallery'

end

app/views/layouts/_admin_links.html.haml
- if signed_in?
  %ul.main-links.smaller
    .triangle.left
    .triangle.right
    %li
      = link_to 'Admin Panel', admin_path
    %li
      = link_to 'Photos', admin_photos_path
    %li
      = link_to 'Videos', admin_videos_path
    %li
      = link_to 'Blog Posts', admin_blog_posts_path
    %li
      = link_to 'Links', admin_links_path
    %li
      = link_to 'Sign Out', signout_path, 'data-pjax-ignore' => true

app/views/layouts/_header.html.haml
%header
  .title-area
    %h1= 'Iris McLean'
    %h2= 'the official site'
  %ul.main-links
    .triangle.left
    .triangle.right
    %li
      = link_to 'Home', home_path, :class => "#{"selected" if current_page?(['pages', 'home'])}"
    %li
      = link_to 'Biography', bio_path, :class => "#{"selected" if current_page?(['pages', 'bio'])}"
    %li
      = link_to 'Latest News', news_path, :class => "#{"selected" if current_page?(['pages', 'news'])}"
    %li
      = link_to 'Photos', photos_path, :class => "#{"selected" if current_page?(['pages', 'photos'], ['pages', 'gallery'])}"
    %li
      = link_to 'Videos', videos_path, :class => "#{"selected" if current_page?(['pages', 'videos'])}"
    %li
      = link_to 'Resume', resume_path, :class => "#{"selected" if current_page?(['pages', 'resume'])}"
    %li
      = link_to 'Links', links_path, :class => "#{"selected" if current_page?(['pages', 'links'])}"
    %li
      = link_to 'Contact Me', contact_path, :class => "#{"selected" if current_page?(['pages', 'contact'])}"

  = render 'layouts/admin_links'

app/views/layouts/ajax_title.html.haml
%title= title

= yield

app/views/layouts/application.html.haml
%html
  %head
    %title= title
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "pages"
    = stylesheet_link_tag    "admin" if signed_in?
    = javascript_include_tag "application"
    = favicon_link_tag "favicon.ico"
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/header'
      .clear
      %section.round
        #content
          = yield

      = render 'layouts/footer'
      = debug(params) if Rails.env.development?